### ISSUE TITLE
Add documentation and/or minimum how to

### ISSUE THREAD

**Issue by Sub-Zero-1** [agustinus/react-native-dynamic-yield#1]
Actually there is no documentation provided. The example code only shows how to get dynamicVariable which I suppose is getSmartVariable according to the official dynamicYield documentation? 
How to get product recommendations as per offical documenation: sendRecommendationRequest() ?

**Comment by agustinus** [comment]
Sorry I still have no time to make the typescript interface for this module. But you can refer to this native module for all the export methods from DY SDK:
https://github.com/agustinus/react-native-dynamic-yield/blob/master/android/src/main/java/com/reactlibrarydynamicyield/RNDynamicYieldModule.java
or
https://github.com/agustinus/react-native-dynamic-yield/blob/master/ios/RNDynamicYield.m

As for getDynamicVariable, yes it's getSmartVariable from the SDK. I got this term from the documentation back then. You can refer to https://github.com/agustinus/react-native-dynamic-yield/blob/021b688a9858a35550b31a65c49455b6e32115af/ios/RNDynamicYield.m#L179

As for sendRecommendationRequest:
https://github.com/agustinus/react-native-dynamic-yield/blob/021b688a9858a35550b31a65c49455b6e32115af/ios/RNDynamicYield.m#L152

Which line of code is this error from?
`error: typerror: TypeError: Cannot read property 'toString' of undefined.`
I can't see it comes from this module, could you elaborate more on this error?

In my case, I'm calling this:
`DynamicYield.sendRecommendationRequest('101910', DynamicYield.DY_TYPE_PRODUCT, 'en', ['1461525']);
`
or

`DynamicYield.sendRecommendationRequest('101910', DynamicYield.DY_TYPE_HOMEPAGE, 'en', []);`

**Comment by Sub-Zero-1** [comment]
Thanks for the answer!

I can now get it to work and the sendRecommendationRequest doesn't give me an error message back! So it seems to work. I still can't test it completly(dynamic variable works!), as I would have to have a complete mobile app setup on the dynamic yield website. DynamicYield told use before, that they are able to generate API Keys(secret key) for our website project, so we could access the website project with your lib (within mobile apps), but now they told us that it is not possible. With help of native API request (e.g. curl) we can use our already existing web project without setting up all again just for the mobile apps. So we will most likely go for the native API requests.

**Comment by agustinus** [comment]
If it's purely web project, then this module is not for you of course. This module is totally rely on Android and iOS native sdk. Ok, good luck for the implementation. And thanks for the feedback.
